In [6]:
import numpy as np
# generate numpy matrix of 3x3
# add to it row wise 
# add to it column wise
global scaling
n=3
vector_1=np.random.rand(n,1)
theta=(np.pi/6)
rot_2_1=np.asarray([[np.cos(theta),-np.sin(theta),0],[np.sin(theta),np.cos(theta),0],[0,0,1]])
trans_2_1=np.asarray([[4,3,1]]).transpose()
# print(trans_2_1.shape)
print(trans_2_1)
# print(vector_2)
T_2_1=np.hstack((rot_2_1,trans_2_1))
print(T_2_1)
scaling=np.asarray([[0,0,0,1]])
T_2_1=np.vstack((T_2_1,scaling))
print(T_2_1.shape)

[[4]
 [3]
 [1]]
[[ 0.8660254 -0.5        0.         4.       ]
 [ 0.5        0.8660254  0.         3.       ]
 [ 0.         0.         1.         1.       ]]
(4, 4)


In [7]:
# find inverse
print(T_2_1)
print(T_2_1[:-1,:-1])
print(np.asarray([T_2_1[:-1,-1]]).transpose())
print(T_2_1[:-1,:-1].shape)
# def inverse(T):
#     global scaling
#     R_o_f=T[:-1,:-1].transpose()
#     Tran_o_f=-R_o_f@(np.asarray([T_2_1[:-1,-1]]).transpose())
#     T_o_f=np.hstack(R_o_f,Tran_o_f)
#     T_o_f=np.vstack(T_o_f,scaling)
#     return T_o_f
# T_1_2= inverse(T_2_1)
# print(T_1_2)   
    

[[ 0.8660254 -0.5        0.         4.       ]
 [ 0.5        0.8660254  0.         3.       ]
 [ 0.         0.         1.         1.       ]
 [ 0.         0.         0.         1.       ]]
[[ 0.8660254 -0.5        0.       ]
 [ 0.5        0.8660254  0.       ]
 [ 0.         0.         1.       ]]
[[4.]
 [3.]
 [1.]]
(3, 3)


In [9]:
# print(np.cos(np.pi/3))
rot=np.pi/6
A_R_B=np.array([[np.cos(rot),-np.sin(rot), 0],[np.sin(rot),np.cos(rot), 0],[0,0, 1]])
print(A_R_B)

B_P=np.array([[3.07],[0],[0]])
B_P.shape

# translation of axis
A_P_Borg=np.array([[10],[5],[0]])
A_P_Borg=np.append(A_P_Borg,np.array([1]).reshape([1,1]),axis=0)
print(A_P_Borg.shape)
print(A_P_Borg)


#  point information
B_P=np.array([[3.07],[0],[0],[1]])

# translation matrix
a_T_b=np.append(A_R_B,np.zeros([1,3]),axis=0)
a_T_b=np.append(a_T_b,A_P_Borg,axis=1)


print(a_T_b)
new_A_p=a_T_b@B_P
print(new_A_p)

[[ 0.8660254 -0.5        0.       ]
 [ 0.5        0.8660254  0.       ]
 [ 0.         0.         1.       ]]
(4, 1)
[[10]
 [ 5]
 [ 0]
 [ 1]]
[[ 0.8660254 -0.5        0.        10.       ]
 [ 0.5        0.8660254  0.         5.       ]
 [ 0.         0.         1.         0.       ]
 [ 0.         0.         0.         1.       ]]
[[12.65869799]
 [ 6.535     ]
 [ 0.        ]
 [ 1.        ]]


In [ ]:
# import numpy as np

# # 1. Generate vectors of Nx1 size
# N = 4
# vector_n1 = np.random.rand(N, 1)
# print("Vector of size Nx1:\n", vector_n1)

# # 2. Generate a numpy matrix of NxM of all ones
# M = 3
# matrix_ones = np.ones((N, M))
# print("\nMatrix of NxM with all ones:\n", matrix_ones)

# # 3. Generate column-wise vectors and add them side by side (example: 3 vectors)
# vector_1 = np.random.rand(N, 1)
# vector_2 = np.random.rand(N, 1)
# vector_3 = np.random.rand(N, 1)

# side_by_side = np.hstack((vector_1, vector_2, vector_3))
# print("\nColumn-wise vectors added side by side:\n", side_by_side)

# # 4. Add vectors row-wise
# row_wise = np.vstack((vector_1.T, vector_2.T, vector_3.T))
# print("\nVectors added row-wise:\n", row_wise)

# # 5. Add vectors column-wise
# column_wise = np.hstack((vector_1, vector_2, vector_3))
# print("\nVectors added column-wise:\n", column_wise)

# # 6. Dot product of two vectors
# vector_a = np.random.rand(N, 1)
# vector_b = np.random.rand(N, 1)

# dot_product = np.dot(vector_a.T, vector_b)
# print("\nDot product of two vectors:\n", dot_product)

# # 7. Multiplication of two matrices
# matrix_a = np.random.rand(N, M)
# matrix_b = np.random.rand(M, N)

# matrix_multiplication = np.dot(matrix_a, matrix_b)
# print("\nMultiplication of two matrices:\n", matrix_multiplication)