In [1]:
import torch
k=torch.arange(0, 5, 2)
print(k)

tensor([0, 2, 4])


In [7]:
embd_dim=50
seq_len=10
pe = torch.zeros(seq_len, embd_dim) # position encoding matrix
position = torch.arange(0, seq_len, dtype=torch.float).unsqueeze(1) # dimension (seq_len,1)
print(position.shape)
div_term = torch.exp(torch.arange(0, embd_dim, 2).float() * (-torch.log(torch.tensor(10000.0)) / embd_dim))
# print(div_term.shape)
# print((position * div_term).shape)
# print(position * div_term)
pe[:, 0::2] = torch.sin(position * div_term)
pe[:, 1::2] = torch.cos(position * div_term)

pe.shape

torch.Size([10, 1])


torch.Size([10, 50])

In [14]:
b,t,c=3,2,4
a=torch.ones(b,t,c)
print(a.shape)
# print(a.sum(dim=-1))
# print(a.sum(dim=-1,keepdim=True))

torch.Size([3, 2, 4])
tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])
tensor([[[4.],
         [4.]],

        [[4.],
         [4.]],

        [[4.],
         [4.]]])
